import Defs.IsPrime
import Mathlib.Tactic

/-! Hole `prime_divisor` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem infinitude_of_primes__h2 : ∀ (n : ℕ),
  (∀ (k : ℕ), 0 < k → k ≤ n → Opn.Divides k n.factorial) → ∀ (m : ℕ), 2 ≤ m → ∃ p, Opn.IsPrime p ∧ Opn.Divides p m := by
  intro _ _ m
  -- Strong induction on m: m is prime, or it has a proper divisor d with 2 ≤ d < m.
  induction m using Nat.strongRecOn with
  | _ m ih =>
    intro hm
    by_cases hp : Opn.IsPrime m
    · exact ⟨m, hp, 1, (Nat.mul_one m).symm⟩
    · have hnot : ¬ ∀ d : Nat, Opn.Divides d m → d = 1 ∨ d = m := fun h => hp ⟨hm, h⟩
      push_neg at hnot
      obtain ⟨d, ⟨c, hc⟩, hd1, hdm⟩ := hnot
      have hd0 : d ≠ 0 := by
        intro h
        rw [h, Nat.zero_mul] at hc
        omega
      have hdle : d ≤ m := Nat.le_of_dvd (by omega) ⟨c, hc⟩
      obtain ⟨p, hpp, a, ha⟩ := ih d (by omega) (by omega)
      exact ⟨p, hpp, a * c, by rw [hc, ha, Nat.mul_assoc]⟩
