import Defs.IsPrime
import Mathlib.Tactic

/-! Hole `dvd_fact` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem infinitude_of_primes__h1 : ∀ (n k : ℕ), 0 < k → k ≤ n → Opn.Divides k n.factorial := by
  intro n k hk hkn
  -- Mathlib: a positive k ≤ n divides n!; `Opn.Divides` is the same ∃-statement.
  obtain ⟨c, hc⟩ := Nat.dvd_factorial hk hkn
  exact ⟨c, hc⟩
