import Defs.IsPrime
import Mathlib.Tactic

/-! Hole `dvd_consecutive` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem infinitude_of_primes__h3 : ∀ (n : ℕ),
  (∀ (k : ℕ), 0 < k → k ≤ n → Opn.Divides k n.factorial) →
    (∀ (m : ℕ), 2 ≤ m → ∃ p, Opn.IsPrime p ∧ Opn.Divides p m) →
      ∀ (d m : ℕ), Opn.Divides d m → Opn.Divides d (m + 1) → d = 1 := by
  intro _ _ _ d m hdm hdm1
  -- `Opn.Divides` unfolds to core `∣`; d ∣ m and d ∣ m + 1 give d ∣ 1.
  have h1 : d ∣ m := hdm
  have h2 : d ∣ m + 1 := hdm1
  exact Nat.dvd_one.mp ((Nat.dvd_add_right h1).mp h2)
